import turtle

turtle.forward(50)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.left(90)
turtle.forward(50)
turtle.penup()
turtle.goto(0, 0)

turtle.hideturtle()
turtle.done()
